export const Videos = [
    {
        id:1,
        categorieId:1,
        titre:"Actualites",
        description:"bla bla",
        image:require("../images/actualites.jpeg"),
        tendances:"0",
        date:"01/01/2020",
    },
    {
        id:2,
        categorieId:2,
        titre:"Musique",
        description:"bla bla",
        image:require("../images/musicNote.jpg"),
        tendances:"1",
        date:"02/02/2020",
    },
    {
        id:3,
        categorieId:3,
        titre:"Film",
        description:"bla bla",
        image:require("../images/movieLogo.webp"),
        tendances:"2",
        date:"03/03/2020",
    },
    {
        id:4,
        categorieId:4,
        titre:"Jeux Vidéo",
        description:"bla bla",
        image:require("../images/videoGames.jpg"),
        tendances:"2",
        date:"04/03/2020",
    },
    {
        id:5,
        categorieId:2,
        titre:"Musique",
        description:"bla bla",
        image:require("../images/musicNote.jpg"),
        tendances:"2",
        date:"05/03/2020",
    },
    {
        id:6,
        categorieId:3,
        titre:"Film",
        description:"bla bla",
        image:require("../images/movieLogo.webp"),
        tendances:"2",
        date:"06/03/2020",
    },
    {
        id:7,
        categorieId:1,
        titre:"Botube 7 ",
        description:"bla bla",
        image:require("../images/actualites.jpeg"),
        tendances:"2",
        date:"07/03/2020",
    },
    {
        id:8,
        categorieId:2,
        titre:"Botube 8 ",
        description:"bla bla",
        image:require("../images/musicNote.jpg"),
        tendances:"2",
        date:"08/03/2020",
    },
    {
        id:9,
        categorieId:3,
        titre:"Botube 9 ",
        description:"bla bla",
        image:require("../images/movieLogo.webp"),
        tendances:"2",
        date:"09/03/2020",
    },
    {
        id:10,
        categorieId:1,
        titre:"Botube 10 ",
        description:"bla bla",
        image:require("../images/actualites.jpeg"),
        tendances:"2",
        date:"10/03/2020",
    },
]