export const Videos = [
    {
        id:1,
        categorieId:1,
        titre:"Actualités",
        nom: "MasterGuGu craque",
        description:"En effet apres moult agression verbale MasterGuGu menace de quitté l'imfpa si il est agressé de nouveau.",
        image:require("../images/actualites.jpeg"),
        tendances:"0",
        date:"01/01/2020",
    },
    {
        id:2,
        categorieId:2,
        titre:"Musique",
        nom:"Dj Takaï au platine",
        description:"Enorme festival, Dj TaKaî a mit le feu.",
        image:require("../images/music-maker.webp"),
        tendances:"1",
        date:"02/02/2020",
    },
    {
        id:3,
        categorieId:3,
        titre:"Film",
        nom:" Le jeune Sloan",
        description:"L'histoire d'un jeune garçon qui décide de tout plaquer pour entamer une carrière de clown.",
        image:require("../images/movieLogo.webp"),
        tendances:"2",
        date:"03/03/2020",
    },
    {
        id:4,
        categorieId:4,
        titre:"Jeux Vidéo",
        nom:"Veroniktu",
        description:"Veroniktu le jeu ou il faut tout niquer",
        image:require("../images/videoGames.jpg"),
        tendances:"2",
        date:"04/03/2020",
    },
    {
        id:5,
        categorieId:2,
        titre:"Musique",
        nom:"Musique classique",
        description:"Lorem ipsum stradivarius.",
        image:require("../images/ondes.webp"),
        tendances:"2",
        date:"05/03/2020",
    },
    {
        id:6,
        categorieId:3,
        titre:"Film",
        nom:" A l'affiche",
        description:"Les sorties de la semaine.",
        image:require("../images/movietheater.webp"),
        tendances:"2",
        date:"06/03/2020",
    },
    {
        id:7,
        categorieId:1,
        titre:"Actu.fr",
        nom: "",
        description:"bla bla",
        image:require("../images/actu.fr.png"),
        tendances:"2",
        date:"07/03/2020",
    },
    {
        id:8,
        categorieId:2,
        titre:"Botube 8 ",
        nom:"Le nouveau son de BarryBlack",
        description:"bla bla",
        image:require("../images/musicNote.jpg"),
        tendances:"2",
        date:"08/03/2020",
    },
    {
        id:9,
        categorieId:3,
        titre:"Botube 9 ",
        nom:" Le jeune Sloan",
        description:"bla bla",
        image:require("../images/movieLogo.webp"),
        tendances:"2",
        date:"09/03/2020",
    },
    {
        id:10,
        categorieId:1,
        titre:"Breaking News",
        nom: "MasterGuGu ne veut plus que l' on crie sur lui",
        description:"bla bla",
        image:require("../images/breackingNews.jpg"),
        tendances:"2",
        date:"10/03/2020",
    },
]