export const Videos = [
    {
        id:1,
        categorieId:2,
        titre:"Botube 1",
        description:"bla bla",
        image:"URL",
        tendances:"0",
        date:"01/01/2020",
    },
    {
        id:2,
        categorieId:1,
        titre:"Botube 2 ",
        description:"bla bla",
        image:"URL",
        tendances:"1",
        date:"02/02/2020",
    },
    {
        id:3,
        categorieId:3,
        titre:"Botube 3 ",
        description:"bla bla",
        image:"URL",
        tendances:"2",
        date:"03/03/2020",
    },
    {
        id:4,
        categorieId:1,
        titre:"Botube 4 ",
        description:"bla bla",
        image:"URL",
        tendances:"2",
        date:"04/03/2020",
    },
    {
        id:5,
        categorieId:2,
        titre:"Botube 5 ",
        description:"bla bla",
        image:"URL",
        tendances:"2",
        date:"05/03/2020",
    },
    {
        id:6,
        categorieId:3,
        titre:"Botube 6 ",
        description:"bla bla",
        image:"URL",
        tendances:"2",
        date:"06/03/2020",
    },
    {
        id:7,
        categorieId:1,
        titre:"Botube 7 ",
        description:"bla bla",
        image:"URL",
        tendances:"2",
        date:"07/03/2020",
    },
    {
        id:8,
        categorieId:2,
        titre:"Botube 8 ",
        description:"bla bla",
        image:"URL",
        tendances:"2",
        date:"08/03/2020",
    },
    {
        id:9,
        categorieId:3,
        titre:"Botube 9 ",
        description:"bla bla",
        image:"URL",
        tendances:"2",
        date:"09/03/2020",
    },
    {
        id:10,
        categorieId:1,
        titre:"Botube 10 ",
        description:"bla bla",
        image:"URL",
        tendances:"2",
        date:"10/03/2020",
    },
]